training_pipeline_config:
  pipeline_name: mashroom
  artifact_dir: artifact

data_ingestion_config:
  dataset_download_url: https://archive.ics.uci.edu/static/public/73/mushroom.zip
  raw_data_dir: raw_data
  zip_data_dir: zip_data
  ingested_dir: ingested_data
  ingested_train_dir: train
  ingested_test_dir: test 