training_pipeline_config:
  pipeline_name: mashroom
  artifact_dir: artifact

data_ingestion_config:
  dataset_download_url: https://archive.ics.uci.edu/static/public/73/mushroom.zip
  raw_data_dir: raw_data
  zip_data_dir: zip_data
  ingested_dir: ingested_data
  ingested_train_dir: train
  ingested_test_dir: test 

data_validation_config:
  schema_dir : config
  schema_file : schema.yaml
  report_page_file_name : report.html

data_transform_config:
  train_dir : train
  test_dir : test
  preprocessed_object_dir: preprocessed
  preprocessed_object_file_name: preprocessed.pkl