grid_search:
  class: GridSearchCV
  module: sklearn.model_selection
  params:
    cv: 5
    verbose: 2
  
model_selection:
  module_0:
    class: LogisticRegression
    module: sklearn.linear_model
    params:
      penalty: l2
    search_param_grid:
      penalty:
      - l2
